In [1]:
import os
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from preprocessing_functions import *

images_pid, images_image, images_label, images_mask = read_images_to_array('data/images/')
images_label_string = convert_labels_to_strings(images_label)

1070.mat
1071.mat
1072.mat
1073.mat
1074.mat
1075.mat
1076.mat
1203.mat
1204.mat
1205.mat
1206.mat
1207.mat
955.mat
956.mat
957.mat


# train - test split

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(images_image, images_label,
                                                    test_size = 0.20, random_state = 42, shuffle = True)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(2439, 512, 512) (610, 512, 512) (2439,) (610,)


In [3]:
X_val = X_train[:610]
X_train = X_train[610:]

y_val = y_train[:610]
y_train = y_train[610:]

print(X_val.shape, X_train.shape, y_val.shape, y_train.shape)

(610, 512, 512) (1829, 512, 512) (610,) (1829,)


# labels to one hot encoding

In [4]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train)
y_val = to_categorical(y_val)
y_test = to_categorical(y_test)

print(y_train[:5])
print(y_train.shape, y_val.shape, y_test.shape)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(1829, 3) (610, 3) (610, 3)
